// <auto-generated />
namespace AngolaPrev.VivaEstetica.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class att_tbservicos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(att_tbservicos));
        
        string IMigrationMetadata.Id
        {
            get { return "201902120043329_att_tbservicos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
