// <auto-generated />
namespace AngolaPrev.VivaEstetica.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class qt_sessoes_agendamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qt_sessoes_agendamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201902130136390_qt_sessoes_agendamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
